### ISSUE TITLE
Newsboat config not working - Headers and footers

### ISSUE THREAD

**Issue by ghost** [NapoleonWils0n/ubuntu-dotfiles#1]
Despite copying your .config file in my newsboat the looks of newsboat does not change. I want the same headers look you show in your video.

**Comment by NapoleonWils0n** [comment]
HI Mate, i changed my newsboat config since i made that video and commented out the code

But you can still still see the config files in my git history and download them from the links below

[newsboat config](https://github.com/NapoleonWils0n/ubuntu-dotfiles/blob/8d26c2401a3a9a2109acb9238133addd45ac1091/.config/newsboat/config)

[newsboat urls](https://github.com/NapoleonWils0n/ubuntu-dotfiles/blob/8d26c2401a3a9a2109acb9238133addd45ac1091/.config/newsboat/urls)

**Comment by ghost** [comment]
Thanks! And continue making content!
